---

- name: Create yum repository
  yum_repository:
    name: xenithorb-rocketchat
    description: "[COPR] Rocket.Chat - Fedora $releasever - $basearch"
    baseurl: https://copr-be.cloud.fedoraproject.org/results/xenithorb/rocketchat-dev/fedora-$releasever-$basearch/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/xenithorb/rocketchat-dev/pubkey.gpg
    state: present
  become: yes

- name: Install rocketchat
  dnf:
    name: rocketchat-desktop
    state: present
  become: yes
